version: '3.8'

services:
  # ---------------------------------------------------
  # SERVICIOS DE PROCESAMIENTO (PARAMETRIZADOS POR ZONA)
  # ---------------------------------------------------

  spark-br:
    build: .
    container_name: spark-br
    hostname: spark-br
    # 1. Vive SÓLO en la red de Brasil
    networks:
      - zona-br
    # 2. Monta la config
    volumes:
      - ./config:/opt/spark/conf
    # 3. Pasa la variable de entorno
    environment:
      - ZONA_ID=br
    command: ["spark-submit", "--master", "local[*]", "/app/stream-writer.py"]
    
  spark-cl:
    build: .
    container_name: spark-cl
    hostname: spark-cl
    networks:
      - zona-cl
    volumes:
      - ./config:/opt/spark/conf
    environment:
      - ZONA_ID=cl
    command: ["spark-submit", "--master", "local[*]", "/app/stream-writer.py"]

  spark-co:
    build: .
    container_name: spark-co
    hostname: spark-co
    networks:
      - zona-co
    volumes:
      - ./config:/opt/spark/conf
    environment:
      - ZONA_ID=co
    command: ["spark-submit", "--master", "local[*]", "/app/stream-writer.py"]

# ---------------------------------------------------
# CONEXIÓN A REDES EXTERNAS
# ---------------------------------------------------
networks:
  zona-br:
    external: true
    name: custom-hadoop-cluster_zona-br
  zona-cl:
    external: true
    name: custom-hadoop-cluster_zona-cl
  zona-co:
    external: true
    name: custom-hadoop-cluster_zona-co